#!/usr/bin/env bash
# Builds the single file to paste into the Apps Script editor (dist/Code.gs):
# shared business logic + e-mail templates + the server.
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p dist
{
  echo "// ================================================================"
  echo "// AUTO-GENERATED by apps-script/build.sh - do not edit by hand."
  echo "// Source: shared/core.js + shared/email-templates.js + apps-script/src/Server.js"
  echo "// ================================================================"
  cat ../shared/core.js
  echo
  cat ../shared/email-templates.js
  echo
  cat src/Server.js
} > dist/Code.gs
cp appsscript.json dist/appsscript.json
echo "built dist/Code.gs ($(wc -l < dist/Code.gs) lines)"
